server:
  port:
    6281

spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db2023
    driverClassName: org.h2.Driver
    username: h2db
    password: PolliSpring23
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


---
spring:
  config:
    activate:
      on-profile: development
---
spring:
  config:
    activate:
      on-profile: product
---
spring:
  config:
    activate:
      on-profile: test